### ISSUE TITLE
Graphs must be in C++

### ISSUE THREAD

**Issue by Will-huynh13** [AngusFiedler/RestaurantRecommender#9]
According to Piazza and our TA Jason, we can use other languages to visualize our project but the actual data structure part has to be written in C++.

![image](https://user-images.githubusercontent.com/47924673/56341015-fb307880-6170-11e9-995b-27b01d6d2bba.png)

**Comment by AngusFiedler** [comment]
This will be done via platform channels.

Dart code will send data to java through sending binary messages with platform channels.
Java code at that point will simply run a function call to our c++ code and return the result.

IE
Dart call -> Java function -> c++ code -> Java function -> Dart(data returned)

This data is sent asynchronously through this process and requires a return for the callback to be valid.

[Click here](https://medium.com/flutter-io/flutter-platform-channels-ce7f540a104e) for a full rundown of Platform channels



![image](https://user-images.githubusercontent.com/35715801/56376910-5e002f00-61c6-11e9-8fa9-06017d5718d3.png)

**Comment by AngusFiedler** [comment]
Change of plans, this will be done via web server, issue closed
